// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutHub.Data;

#nullable disable

namespace WorkoutHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WorkoutHub.Entities.WorkoutExercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutHub.Models.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Description = "Upper body pushing exercise targeting chest, shoulders, and triceps",
                            Name = "Push-ups"
                        },
                        new
                        {
                            Id = "2",
                            Description = "Lower body compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats"
                        },
                        new
                        {
                            Id = "3",
                            Description = "Full body compound exercise targeting back, glutes, and hamstrings",
                            Name = "Deadlifts"
                        },
                        new
                        {
                            Id = "4",
                            Description = "Upper body pressing exercise targeting chest, shoulders, and triceps",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = "5",
                            Description = "Upper body pulling exercise targeting back and biceps",
                            Name = "Pull-ups"
                        },
                        new
                        {
                            Id = "6",
                            Description = "Upper back and bicep exercise",
                            Name = "Rows"
                        },
                        new
                        {
                            Id = "7",
                            Description = "Core stability exercise",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = "8",
                            Description = "Lower body exercise targeting quads, glutes, and hamstrings",
                            Name = "Lunges"
                        });
                });

            modelBuilder.Entity("WorkoutHub.Models.ScheduledWorkout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("ScheduledWorkouts");
                });

            modelBuilder.Entity("WorkoutHub.Models.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutHub.Models.WorkoutPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("WorkoutHub.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutHub.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutHub.Models.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutHub.Models.ScheduledWorkout", b =>
                {
                    b.HasOne("WorkoutHub.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutHub.Models.WorkoutPlan", null)
                        .WithMany("ScheduledWorkoutList")
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutHub.Models.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutHub.Models.WorkoutPlan", b =>
                {
                    b.Navigation("ScheduledWorkoutList");
                });
#pragma warning restore 612, 618
        }
    }
}
